language: elixir
elixir:
- 1.0.0
- 1.0.1
- 1.0.2
- 1.0.3
- 1.0.4
- 1.0.5
- 1.1.0
- 1.1.1
- 1.2.0
otp_release:
- 18.2
- 18.1
- 18.0
- 17.4
- 17.3
- 17.1
- 17.0
sudo: false
install: true

before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - mkdir -p _plt
  - mix do archive.build, archive.install --force

script: 
  - "MIX_ENV=prod mix do deps.clean --all, deps.get, compile, hex.build"
  - "MIX_ENV=test mix do test --trace, dialyzer "


cache:
  directories:
  - $HOME/.mix/archives
